name: Hexo Deploy

# 触发条件: push到Master分支后自动触发
on:
  push:
    branches:
      - master

jobs:
  build:
    name: BDLDoc Build & Delpoy
    # 使用Ubuntu-18.04作为编译部署环境
    runs-on: ubuntu-18.04 

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      # 设置Node.js环境
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      # 设置包缓存目录
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # 配置Hexo运行安装环境
      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "2801621420@qq.com"
          git config --global user.name "Superice666"
          npm install hexo-cli -g
          npm install

      #编译MarkDown文件 (预留) 
      #- name: Generate files
      #run: |
      #  hexo clean
      #  hexo generate

      # 部署Hexo至gh-pages分支下    
      - name: Deploy
        run: |
          hexo clean
          hexo deploy